export const APP_CONFIG = {
  storageKey: "momos_elder_assessments_v1",
  pdf: {
    title: "Elder Health Assessment Report",
    subtitle: "Generated by MOMOs-style screening tool (Questionnaire-based)",
    filePrefix: "Elder_Report_",
  },
};
